tag: lava-maze-v1
general:
  - config:
      name: Lava Maze
      log_path: ./logs
      checkpoint_path: ./checkpoints
      terminal_reward: 85
      step_reward: -1
      client_port: 9000  # malmo port
      time_wait: 0.05  # time to wait for retreiving world state (when MsPerTick=20)
      max_loop: 50  # wait till TIME_WAIT * MAX_LOOP seconds for each action
      action_space:
        0: move 0  # don't move
        1: move 1  # move forward
        2: move -1  # move backward
        3: strafe 1  # move right
        4: strafe -1  # move left
        5: turn 1  # turn right
        6: turn -1  # turn left
tuner:
  - config:
      log_level: WARN
      env: lava_maze_1
      env_config:
        mission_file: missions/lava_maze.xml
        width: 84
        height: 84
        millisec_per_tick: 20
      framework: tf
      num_gpus: 0
      num_workers: 1
      double_q: True
      dueling: True
      explore: True
      exploration_config:
        type: EpsilonGreedy
        initial_epsilon: 1.0
        final_epsilon: 0.02
        epsilon_timesteps: 100
    type: ray
