tag: lure-creeper-v1
general:
  - config:
      name: Lure Creeper
      log_path: ./logs
      checkpoint_path: ./checkpoints
      step_reward: -1
      win_reward: 85
      lose_reward: 85
      client_port: 9000  # malmo port
      # mission_timeout_ms: 300000 # This is a good timeout for the maze
      mission_timeout_ms: 30000000 # temporary
      time_wait: 0.05  # time to wait for retreiving world state (when MsPerTick=20)
      max_loop: 50  # wait till TIME_WAIT * MAX_LOOP seconds for each action
      action_space:  # The order of the actions is rettained in the action space
        - move 1  # move forward
        - move -1  # move backward
        - strafe 1  # move right
        - strafe -1  # move left
        - turn 1  # turn right
        - turn -1  # turn left
tuner:
  - config:
      log_level: WARN
      env: lure_creeper_1
      env_config:
        mission_file: missions/lure_creeper.xml
        width: 84
        height: 84
        millisec_per_tick: 20
      framework: tf
      num_gpus: 0
      num_workers: 1
      double_q: True
      dueling: True
      explore: True
      exploration_config:
        type: EpsilonGreedy
        initial_epsilon: 1.0
        final_epsilon: 0.02
        epsilon_timesteps: 100
    type: ray
